services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 443:443
      - 80:80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
